#include "dpic.h"
/*Generated by DPIC-fw. Do NOT edit.*/
extern "C" {

void dpic_InsrtCommit_override(
  uint8_t  io_index,
  uint8_t  io_valid,
  unsopproted io_pc,
  uint32_t io_instr,
  uint8_t  io_skip,
  uint8_t  io_wen,
  uint8_t  io_wdest,
  unsopproted io_wdata,
  uint8_t  io_csrRstat,
  uint32_t io_csrData)
__attribute__ ((weak));

void dpic_ExcpEvent_override(
  uint8_t  io_excp_valid,
  uint8_t  io_isMret,
  uint32_t io_intrptNo,
  uint32_t io_cause,
  unsopproted io_exceptionPC,
  uint32_t io_exceptionInst)
__attribute__ ((weak));

void dpic_LoadEvent_override(
  uint8_t  io_index,
  uint8_t  io_valid,
  unsopproted io_paddr,
  unsopproted io_vaddr,
  unsopproted io_data)
__attribute__ ((weak));

void dpic_StoreEvent_override(
  uint8_t  io_index,
  uint8_t  io_valid,
  unsopproted io_paddr,
  unsopproted io_vaddr,
  unsopproted io_data)
__attribute__ ((weak));

void dpic_CSRRegState_override(
  unsopproted io_mstatus,
  unsopproted io_mtvec,
  unsopproted io_mepc,
  unsopproted io_mcause)
__attribute__ ((weak));

void dpic_GRegState_override(
  unsopproted io_gpr_0,
  unsopproted io_gpr_1,
  unsopproted io_gpr_2,
  unsopproted io_gpr_3,
  unsopproted io_gpr_4,
  unsopproted io_gpr_5,
  unsopproted io_gpr_6,
  unsopproted io_gpr_7,
  unsopproted io_gpr_8,
  unsopproted io_gpr_9,
  unsopproted io_gpr_10,
  unsopproted io_gpr_11,
  unsopproted io_gpr_12,
  unsopproted io_gpr_13,
  unsopproted io_gpr_14,
  unsopproted io_gpr_15,
  unsopproted io_gpr_16,
  unsopproted io_gpr_17,
  unsopproted io_gpr_18,
  unsopproted io_gpr_19,
  unsopproted io_gpr_20,
  unsopproted io_gpr_21,
  unsopproted io_gpr_22,
  unsopproted io_gpr_23,
  unsopproted io_gpr_24,
  unsopproted io_gpr_25,
  unsopproted io_gpr_26,
  unsopproted io_gpr_27,
  unsopproted io_gpr_28,
  unsopproted io_gpr_29,
  unsopproted io_gpr_30,
  unsopproted io_gpr_31)
__attribute__ ((weak));

struct dpic_InsrtCommit_data_struct dpic_InsrtCommit_data;

void dpic_InsrtCommit(
  uint8_t  io_index,
  uint8_t  io_valid,
  unsopproted io_pc,
  uint32_t io_instr,
  uint8_t  io_skip,
  uint8_t  io_wen,
  uint8_t  io_wdest,
  unsopproted io_wdata,
  uint8_t  io_csrRstat,
  uint32_t io_csrData
) {
  if(dpic_InsrtCommit_override != nullptr){
   dpic_InsrtCommit_override(io_index, io_valid, io_pc, io_instr, io_skip, io_wen, io_wdest, io_wdata, io_csrRstat, io_csrData);
   return;
  }
  auto packet = dpic_InsrtCommit_data;
  dpic_InsrtCommit_data.index = io_index;
  dpic_InsrtCommit_data.valid = io_valid;
  dpic_InsrtCommit_data.pc = io_pc;
  dpic_InsrtCommit_data.instr = io_instr;
  dpic_InsrtCommit_data.skip = io_skip;
  dpic_InsrtCommit_data.wen = io_wen;
  dpic_InsrtCommit_data.wdest = io_wdest;
  dpic_InsrtCommit_data.wdata = io_wdata;
  dpic_InsrtCommit_data.csrRstat = io_csrRstat;
  dpic_InsrtCommit_data.csrData = io_csrData;
}

struct dpic_ExcpEvent_data_struct dpic_ExcpEvent_data;

void dpic_ExcpEvent(
  uint8_t  io_excp_valid,
  uint8_t  io_isMret,
  uint32_t io_intrptNo,
  uint32_t io_cause,
  unsopproted io_exceptionPC,
  uint32_t io_exceptionInst
) {
  if(dpic_ExcpEvent_override != nullptr){
   dpic_ExcpEvent_override(io_excp_valid, io_isMret, io_intrptNo, io_cause, io_exceptionPC, io_exceptionInst);
   return;
  }
  auto packet = dpic_ExcpEvent_data;
  dpic_ExcpEvent_data.excp_valid = io_excp_valid;
  dpic_ExcpEvent_data.isMret = io_isMret;
  dpic_ExcpEvent_data.intrptNo = io_intrptNo;
  dpic_ExcpEvent_data.cause = io_cause;
  dpic_ExcpEvent_data.exceptionPC = io_exceptionPC;
  dpic_ExcpEvent_data.exceptionInst = io_exceptionInst;
}

struct dpic_LoadEvent_data_struct dpic_LoadEvent_data;

void dpic_LoadEvent(
  uint8_t  io_index,
  uint8_t  io_valid,
  unsopproted io_paddr,
  unsopproted io_vaddr,
  unsopproted io_data
) {
  if(dpic_LoadEvent_override != nullptr){
   dpic_LoadEvent_override(io_index, io_valid, io_paddr, io_vaddr, io_data);
   return;
  }
  auto packet = dpic_LoadEvent_data;
  dpic_LoadEvent_data.index = io_index;
  dpic_LoadEvent_data.valid = io_valid;
  dpic_LoadEvent_data.paddr = io_paddr;
  dpic_LoadEvent_data.vaddr = io_vaddr;
  dpic_LoadEvent_data.data = io_data;
}

struct dpic_StoreEvent_data_struct dpic_StoreEvent_data;

void dpic_StoreEvent(
  uint8_t  io_index,
  uint8_t  io_valid,
  unsopproted io_paddr,
  unsopproted io_vaddr,
  unsopproted io_data
) {
  if(dpic_StoreEvent_override != nullptr){
   dpic_StoreEvent_override(io_index, io_valid, io_paddr, io_vaddr, io_data);
   return;
  }
  auto packet = dpic_StoreEvent_data;
  dpic_StoreEvent_data.index = io_index;
  dpic_StoreEvent_data.valid = io_valid;
  dpic_StoreEvent_data.paddr = io_paddr;
  dpic_StoreEvent_data.vaddr = io_vaddr;
  dpic_StoreEvent_data.data = io_data;
}

struct dpic_CSRRegState_data_struct dpic_CSRRegState_data;

void dpic_CSRRegState(
  unsopproted io_mstatus,
  unsopproted io_mtvec,
  unsopproted io_mepc,
  unsopproted io_mcause
) {
  if(dpic_CSRRegState_override != nullptr){
   dpic_CSRRegState_override(io_mstatus, io_mtvec, io_mepc, io_mcause);
   return;
  }
  auto packet = dpic_CSRRegState_data;
  dpic_CSRRegState_data.mstatus = io_mstatus;
  dpic_CSRRegState_data.mtvec = io_mtvec;
  dpic_CSRRegState_data.mepc = io_mepc;
  dpic_CSRRegState_data.mcause = io_mcause;
}

struct dpic_GRegState_data_struct dpic_GRegState_data;

void dpic_GRegState(
  unsopproted io_gpr_0,
  unsopproted io_gpr_1,
  unsopproted io_gpr_2,
  unsopproted io_gpr_3,
  unsopproted io_gpr_4,
  unsopproted io_gpr_5,
  unsopproted io_gpr_6,
  unsopproted io_gpr_7,
  unsopproted io_gpr_8,
  unsopproted io_gpr_9,
  unsopproted io_gpr_10,
  unsopproted io_gpr_11,
  unsopproted io_gpr_12,
  unsopproted io_gpr_13,
  unsopproted io_gpr_14,
  unsopproted io_gpr_15,
  unsopproted io_gpr_16,
  unsopproted io_gpr_17,
  unsopproted io_gpr_18,
  unsopproted io_gpr_19,
  unsopproted io_gpr_20,
  unsopproted io_gpr_21,
  unsopproted io_gpr_22,
  unsopproted io_gpr_23,
  unsopproted io_gpr_24,
  unsopproted io_gpr_25,
  unsopproted io_gpr_26,
  unsopproted io_gpr_27,
  unsopproted io_gpr_28,
  unsopproted io_gpr_29,
  unsopproted io_gpr_30,
  unsopproted io_gpr_31
) {
  if(dpic_GRegState_override != nullptr){
   dpic_GRegState_override(io_gpr_0, io_gpr_1, io_gpr_2, io_gpr_3, io_gpr_4, io_gpr_5, io_gpr_6, io_gpr_7, io_gpr_8, io_gpr_9, io_gpr_10, io_gpr_11, io_gpr_12, io_gpr_13, io_gpr_14, io_gpr_15, io_gpr_16, io_gpr_17, io_gpr_18, io_gpr_19, io_gpr_20, io_gpr_21, io_gpr_22, io_gpr_23, io_gpr_24, io_gpr_25, io_gpr_26, io_gpr_27, io_gpr_28, io_gpr_29, io_gpr_30, io_gpr_31);
   return;
  }
  auto packet = dpic_GRegState_data;
  dpic_GRegState_data.gpr_0 = io_gpr_0;
  dpic_GRegState_data.gpr_1 = io_gpr_1;
  dpic_GRegState_data.gpr_2 = io_gpr_2;
  dpic_GRegState_data.gpr_3 = io_gpr_3;
  dpic_GRegState_data.gpr_4 = io_gpr_4;
  dpic_GRegState_data.gpr_5 = io_gpr_5;
  dpic_GRegState_data.gpr_6 = io_gpr_6;
  dpic_GRegState_data.gpr_7 = io_gpr_7;
  dpic_GRegState_data.gpr_8 = io_gpr_8;
  dpic_GRegState_data.gpr_9 = io_gpr_9;
  dpic_GRegState_data.gpr_10 = io_gpr_10;
  dpic_GRegState_data.gpr_11 = io_gpr_11;
  dpic_GRegState_data.gpr_12 = io_gpr_12;
  dpic_GRegState_data.gpr_13 = io_gpr_13;
  dpic_GRegState_data.gpr_14 = io_gpr_14;
  dpic_GRegState_data.gpr_15 = io_gpr_15;
  dpic_GRegState_data.gpr_16 = io_gpr_16;
  dpic_GRegState_data.gpr_17 = io_gpr_17;
  dpic_GRegState_data.gpr_18 = io_gpr_18;
  dpic_GRegState_data.gpr_19 = io_gpr_19;
  dpic_GRegState_data.gpr_20 = io_gpr_20;
  dpic_GRegState_data.gpr_21 = io_gpr_21;
  dpic_GRegState_data.gpr_22 = io_gpr_22;
  dpic_GRegState_data.gpr_23 = io_gpr_23;
  dpic_GRegState_data.gpr_24 = io_gpr_24;
  dpic_GRegState_data.gpr_25 = io_gpr_25;
  dpic_GRegState_data.gpr_26 = io_gpr_26;
  dpic_GRegState_data.gpr_27 = io_gpr_27;
  dpic_GRegState_data.gpr_28 = io_gpr_28;
  dpic_GRegState_data.gpr_29 = io_gpr_29;
  dpic_GRegState_data.gpr_30 = io_gpr_30;
  dpic_GRegState_data.gpr_31 = io_gpr_31;
}
}