#ifndef __DPIC_H__
#define __DPIC_H__
/*Generated by DPIC-fw. Do NOT edit.*/
#ifdef __cplusplus
#include <cstdint>
extern "C" {
#else
#include <stdint.h>
#endif


void dpic_InsrtCommit(
  uint8_t  io_index,
  uint8_t  io_valid,
  unsopproted io_pc,
  uint32_t io_instr,
  uint8_t  io_skip,
  uint8_t  io_wen,
  uint8_t  io_wdest,
  unsopproted io_wdata,
  uint8_t  io_csrRstat,
  uint32_t io_csrData
);

void dpic_ExcpEvent(
  uint8_t  io_excp_valid,
  uint8_t  io_isMret,
  uint32_t io_intrptNo,
  uint32_t io_cause,
  unsopproted io_exceptionPC,
  uint32_t io_exceptionInst
);

void dpic_LoadEvent(
  uint8_t  io_index,
  uint8_t  io_valid,
  unsopproted io_paddr,
  unsopproted io_vaddr,
  unsopproted io_data
);

void dpic_StoreEvent(
  uint8_t  io_index,
  uint8_t  io_valid,
  unsopproted io_paddr,
  unsopproted io_vaddr,
  unsopproted io_data
);

void dpic_CSRRegState(
  unsopproted io_mstatus,
  unsopproted io_mtvec,
  unsopproted io_mepc,
  unsopproted io_mcause
);

void dpic_GRegState(
  unsopproted io_gpr_0,
  unsopproted io_gpr_1,
  unsopproted io_gpr_2,
  unsopproted io_gpr_3,
  unsopproted io_gpr_4,
  unsopproted io_gpr_5,
  unsopproted io_gpr_6,
  unsopproted io_gpr_7,
  unsopproted io_gpr_8,
  unsopproted io_gpr_9,
  unsopproted io_gpr_10,
  unsopproted io_gpr_11,
  unsopproted io_gpr_12,
  unsopproted io_gpr_13,
  unsopproted io_gpr_14,
  unsopproted io_gpr_15,
  unsopproted io_gpr_16,
  unsopproted io_gpr_17,
  unsopproted io_gpr_18,
  unsopproted io_gpr_19,
  unsopproted io_gpr_20,
  unsopproted io_gpr_21,
  unsopproted io_gpr_22,
  unsopproted io_gpr_23,
  unsopproted io_gpr_24,
  unsopproted io_gpr_25,
  unsopproted io_gpr_26,
  unsopproted io_gpr_27,
  unsopproted io_gpr_28,
  unsopproted io_gpr_29,
  unsopproted io_gpr_30,
  unsopproted io_gpr_31
);

struct dpic_InsrtCommit_data_struct {
  uint8_t  index;
  uint8_t  valid;
  unsopproted pc;
  uint32_t instr;
  uint8_t  skip;
  uint8_t  wen;
  uint8_t  wdest;
  unsopproted wdata;
  uint8_t  csrRstat;
  uint32_t csrData;
};
extern struct dpic_InsrtCommit_data_struct dpic_InsrtCommit_data;

struct dpic_ExcpEvent_data_struct {
  uint8_t  excp_valid;
  uint8_t  isMret;
  uint32_t intrptNo;
  uint32_t cause;
  unsopproted exceptionPC;
  uint32_t exceptionInst;
};
extern struct dpic_ExcpEvent_data_struct dpic_ExcpEvent_data;

struct dpic_LoadEvent_data_struct {
  uint8_t  index;
  uint8_t  valid;
  unsopproted paddr;
  unsopproted vaddr;
  unsopproted data;
};
extern struct dpic_LoadEvent_data_struct dpic_LoadEvent_data;

struct dpic_StoreEvent_data_struct {
  uint8_t  index;
  uint8_t  valid;
  unsopproted paddr;
  unsopproted vaddr;
  unsopproted data;
};
extern struct dpic_StoreEvent_data_struct dpic_StoreEvent_data;

struct dpic_CSRRegState_data_struct {
  unsopproted mstatus;
  unsopproted mtvec;
  unsopproted mepc;
  unsopproted mcause;
};
extern struct dpic_CSRRegState_data_struct dpic_CSRRegState_data;

struct dpic_GRegState_data_struct {
  unsopproted gpr_0;
  unsopproted gpr_1;
  unsopproted gpr_2;
  unsopproted gpr_3;
  unsopproted gpr_4;
  unsopproted gpr_5;
  unsopproted gpr_6;
  unsopproted gpr_7;
  unsopproted gpr_8;
  unsopproted gpr_9;
  unsopproted gpr_10;
  unsopproted gpr_11;
  unsopproted gpr_12;
  unsopproted gpr_13;
  unsopproted gpr_14;
  unsopproted gpr_15;
  unsopproted gpr_16;
  unsopproted gpr_17;
  unsopproted gpr_18;
  unsopproted gpr_19;
  unsopproted gpr_20;
  unsopproted gpr_21;
  unsopproted gpr_22;
  unsopproted gpr_23;
  unsopproted gpr_24;
  unsopproted gpr_25;
  unsopproted gpr_26;
  unsopproted gpr_27;
  unsopproted gpr_28;
  unsopproted gpr_29;
  unsopproted gpr_30;
  unsopproted gpr_31;
};
extern struct dpic_GRegState_data_struct dpic_GRegState_data;
#ifdef __cplusplus
}
#endif
#endif // __DPIC_H__
