// Generated by CIRCT firtool-1.56.0
// Standard header to adapt well known macros to our needs.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

module EX_stage(	// @[<stdin>:950:3]
  input         clock,	// @[<stdin>:951:11]
                reset,	// @[<stdin>:952:11]
                EX_IO_pc_sel,	// @[playground/src/EX_stage.scala:6:12]
  input  [11:0] EX_IO_csr_addr,	// @[playground/src/EX_stage.scala:6:12]
  input  [4:0]  EX_IO_csr_cmd,	// @[playground/src/EX_stage.scala:6:12]
  input  [7:0]  EX_IO_st_type,	// @[playground/src/EX_stage.scala:6:12]
  input  [2:0]  EX_IO_ld_type,	// @[playground/src/EX_stage.scala:6:12]
  input         EX_IO_ebreak_flag,	// @[playground/src/EX_stage.scala:6:12]
  input  [1:0]  EX_IO_wb_sel,	// @[playground/src/EX_stage.scala:6:12]
  input  [3:0]  EX_IO_br_type,	// @[playground/src/EX_stage.scala:6:12]
  input         EX_IO_wen,	// @[playground/src/EX_stage.scala:6:12]
  input  [4:0]  EX_IO_rd,	// @[playground/src/EX_stage.scala:6:12]
  input  [3:0]  EX_IO_alu_op,	// @[playground/src/EX_stage.scala:6:12]
  input  [31:0] EX_IO_src1,	// @[playground/src/EX_stage.scala:6:12]
                EX_IO_src2,	// @[playground/src/EX_stage.scala:6:12]
                EX_IO_rdata1,	// @[playground/src/EX_stage.scala:6:12]
                EX_IO_rdata2,	// @[playground/src/EX_stage.scala:6:12]
                EX_IO_nextpc,	// @[playground/src/EX_stage.scala:6:12]
                EX_IO_pc,	// @[playground/src/EX_stage.scala:6:12]
                EX_IO_inst,	// @[playground/src/EX_stage.scala:6:12]
  output        EX_to_ls_pc_sel,	// @[playground/src/EX_stage.scala:6:12]
  output [11:0] EX_to_ls_csr_addr,	// @[playground/src/EX_stage.scala:6:12]
  output [4:0]  EX_to_ls_csr_cmd,	// @[playground/src/EX_stage.scala:6:12]
  output [7:0]  EX_to_ls_st_type,	// @[playground/src/EX_stage.scala:6:12]
  output [2:0]  EX_to_ls_ld_type,	// @[playground/src/EX_stage.scala:6:12]
  output        EX_to_ls_ebreak_flag,	// @[playground/src/EX_stage.scala:6:12]
  output [1:0]  EX_to_ls_wb_sel,	// @[playground/src/EX_stage.scala:6:12]
  output        EX_to_ls_wen,	// @[playground/src/EX_stage.scala:6:12]
  output [4:0]  EX_to_ls_rd,	// @[playground/src/EX_stage.scala:6:12]
  output [31:0] EX_to_ls_rdata2,	// @[playground/src/EX_stage.scala:6:12]
                EX_to_ls_result,	// @[playground/src/EX_stage.scala:6:12]
                EX_to_ls_nextpc,	// @[playground/src/EX_stage.scala:6:12]
                EX_to_ls_pc,	// @[playground/src/EX_stage.scala:6:12]
  output        EX_br_bus_is_jump,	// @[playground/src/EX_stage.scala:6:12]
  output [31:0] EX_br_bus_dnpc	// @[playground/src/EX_stage.scala:6:12]
);

  wire [31:0] _Alu_io_result;	// @[playground/src/EX_stage.scala:12:17]
  wire        rs1_eq_rs2 = EX_IO_rdata1 == EX_IO_rdata2;	// @[playground/src/EX_stage.scala:18:35]
  wire        rs1_lt_rs2_s = $signed(EX_IO_rdata1) < $signed(EX_IO_rdata2);	// @[playground/src/EX_stage.scala:19:42]
  wire        rs1_lt_rs2_u = EX_IO_rdata1 < EX_IO_rdata2;	// @[playground/src/EX_stage.scala:20:36]
  wire        _dpi_func_io_is_jal_T = EX_IO_br_type == 4'h7;	// @[playground/src/EX_stage.scala:22:39]
  wire        _dpi_func_io_func_flag_T_1 = EX_IO_br_type == 4'h8;	// @[playground/src/EX_stage.scala:23:39]
  Alu Alu (	// @[playground/src/EX_stage.scala:12:17]
    .io_op     (EX_IO_alu_op),
    .io_src1   (EX_IO_src1),
    .io_src2   (EX_IO_src2),
    .io_result (_Alu_io_result)
  );
  dpi_func dpi_func (	// @[playground/src/EX_stage.scala:59:22]
    .clock     (clock),
    .reset     (reset),
    .func_flag (_dpi_func_io_is_jal_T | _dpi_func_io_func_flag_T_1),	// @[playground/src/EX_stage.scala:22:39, :23:39, :62:50]
    .is_jal    (_dpi_func_io_is_jal_T),	// @[playground/src/EX_stage.scala:22:39]
    .pc        (EX_IO_nextpc),
    .nextpc    (32'h0),	// @[playground/src/EX_stage.scala:30:47]
    .rd        ({27'h0, EX_IO_rd}),	// @[playground/src/EX_stage.scala:66:17]
    .inst      (EX_IO_inst)
  );
  assign EX_to_ls_pc_sel = EX_IO_pc_sel;	// @[<stdin>:950:3]
  assign EX_to_ls_csr_addr = EX_IO_csr_addr;	// @[<stdin>:950:3]
  assign EX_to_ls_csr_cmd = EX_IO_csr_cmd;	// @[<stdin>:950:3]
  assign EX_to_ls_st_type = EX_IO_st_type;	// @[<stdin>:950:3]
  assign EX_to_ls_ld_type = EX_IO_ld_type;	// @[<stdin>:950:3]
  assign EX_to_ls_ebreak_flag = EX_IO_ebreak_flag;	// @[<stdin>:950:3]
  assign EX_to_ls_wb_sel = EX_IO_wb_sel;	// @[<stdin>:950:3]
  assign EX_to_ls_wen = EX_IO_wen;	// @[<stdin>:950:3]
  assign EX_to_ls_rd = EX_IO_rd;	// @[<stdin>:950:3]
  assign EX_to_ls_rdata2 = EX_IO_rdata2;	// @[<stdin>:950:3]
  assign EX_to_ls_result = _Alu_io_result;	// @[<stdin>:950:3, playground/src/EX_stage.scala:12:17]
  assign EX_to_ls_nextpc = EX_IO_nextpc;	// @[<stdin>:950:3]
  assign EX_to_ls_pc = EX_IO_pc;	// @[<stdin>:950:3]
  assign EX_br_bus_is_jump =
    _dpi_func_io_is_jal_T | _dpi_func_io_func_flag_T_1 | EX_IO_br_type == 4'h3
    & rs1_eq_rs2 | EX_IO_br_type == 4'h6 & ~rs1_eq_rs2 | EX_IO_br_type == 4'h2
    & rs1_lt_rs2_s | EX_IO_br_type == 4'h1 & rs1_lt_rs2_u | EX_IO_br_type == 4'h5
    & ~rs1_lt_rs2_s | EX_IO_br_type == 4'h4 & ~rs1_lt_rs2_u;	// @[<stdin>:950:3, playground/src/EX_stage.scala:18:35, :19:42, :20:36, :22:39, :23:39, :24:{40,50}, :25:{40,50,53}, :26:{40,50}, :27:{40,50}, :28:{40,50,53}, :29:{23,40,50,53}]
  assign EX_br_bus_dnpc =
    EX_IO_br_type == 4'h8
      ? {_Alu_io_result[31:1], 1'h0}
      : EX_IO_br_type == 4'h7 | EX_IO_br_type == 4'h6 | EX_IO_br_type == 4'h5
        | EX_IO_br_type == 4'h4 | EX_IO_br_type == 4'h3 | EX_IO_br_type == 4'h2
        | EX_IO_br_type == 4'h1
          ? _Alu_io_result
          : 32'h0;	// @[<stdin>:950:3, playground/src/EX_stage.scala:12:17, :22:39, :23:39, :24:40, :25:{40,53}, :26:40, :27:40, :28:40, :29:40, :30:47, :39:{18,32}]
endmodule

