// Generated by CIRCT firtool-1.56.0
module EX_stage(	// @[<stdin>:956:3]
  input         clock,	// @[<stdin>:957:11]
                reset,	// @[<stdin>:958:11]
                EX_IO_bits_pc_sel,	// @[playground/src/EX_stage.scala:6:12]
  input  [11:0] EX_IO_bits_csr_addr,	// @[playground/src/EX_stage.scala:6:12]
  input  [4:0]  EX_IO_bits_csr_cmd,	// @[playground/src/EX_stage.scala:6:12]
  input  [7:0]  EX_IO_bits_st_type,	// @[playground/src/EX_stage.scala:6:12]
  input  [2:0]  EX_IO_bits_ld_type,	// @[playground/src/EX_stage.scala:6:12]
  input         EX_IO_bits_ebreak_flag,	// @[playground/src/EX_stage.scala:6:12]
  input  [1:0]  EX_IO_bits_wb_sel,	// @[playground/src/EX_stage.scala:6:12]
  input  [3:0]  EX_IO_bits_br_type,	// @[playground/src/EX_stage.scala:6:12]
  input         EX_IO_bits_wen,	// @[playground/src/EX_stage.scala:6:12]
  input  [4:0]  EX_IO_bits_rd,	// @[playground/src/EX_stage.scala:6:12]
  input  [3:0]  EX_IO_bits_alu_op,	// @[playground/src/EX_stage.scala:6:12]
  input  [31:0] EX_IO_bits_src1,	// @[playground/src/EX_stage.scala:6:12]
                EX_IO_bits_src2,	// @[playground/src/EX_stage.scala:6:12]
                EX_IO_bits_rdata1,	// @[playground/src/EX_stage.scala:6:12]
                EX_IO_bits_rdata2,	// @[playground/src/EX_stage.scala:6:12]
                EX_IO_bits_nextpc,	// @[playground/src/EX_stage.scala:6:12]
                EX_IO_bits_pc,	// @[playground/src/EX_stage.scala:6:12]
                EX_IO_bits_inst,	// @[playground/src/EX_stage.scala:6:12]
  output        EX_to_ls_bits_pc_sel,	// @[playground/src/EX_stage.scala:6:12]
  output [11:0] EX_to_ls_bits_csr_addr,	// @[playground/src/EX_stage.scala:6:12]
  output [4:0]  EX_to_ls_bits_csr_cmd,	// @[playground/src/EX_stage.scala:6:12]
  output [7:0]  EX_to_ls_bits_st_type,	// @[playground/src/EX_stage.scala:6:12]
  output [2:0]  EX_to_ls_bits_ld_type,	// @[playground/src/EX_stage.scala:6:12]
  output        EX_to_ls_bits_ebreak_flag,	// @[playground/src/EX_stage.scala:6:12]
  output [1:0]  EX_to_ls_bits_wb_sel,	// @[playground/src/EX_stage.scala:6:12]
  output        EX_to_ls_bits_wen,	// @[playground/src/EX_stage.scala:6:12]
  output [4:0]  EX_to_ls_bits_rd,	// @[playground/src/EX_stage.scala:6:12]
  output [31:0] EX_to_ls_bits_rdata2,	// @[playground/src/EX_stage.scala:6:12]
                EX_to_ls_bits_result,	// @[playground/src/EX_stage.scala:6:12]
                EX_to_ls_bits_nextpc,	// @[playground/src/EX_stage.scala:6:12]
                EX_to_ls_bits_pc,	// @[playground/src/EX_stage.scala:6:12]
  output        EX_br_bus_is_jump,	// @[playground/src/EX_stage.scala:6:12]
  output [31:0] EX_br_bus_dnpc	// @[playground/src/EX_stage.scala:6:12]
);

  wire [31:0] _Alu_io_result;	// @[playground/src/EX_stage.scala:16:17]
  wire        rs1_eq_rs2 = EX_IO_bits_rdata1 == EX_IO_bits_rdata2;	// @[playground/src/EX_stage.scala:22:40]
  wire        rs1_lt_rs2_s = $signed(EX_IO_bits_rdata1) < $signed(EX_IO_bits_rdata2);	// @[playground/src/EX_stage.scala:23:47]
  wire        rs1_lt_rs2_u = EX_IO_bits_rdata1 < EX_IO_bits_rdata2;	// @[playground/src/EX_stage.scala:24:41]
  wire        _dpi_func_io_is_jal_T = EX_IO_bits_br_type == 4'h7;	// @[playground/src/EX_stage.scala:26:44]
  wire        _dpi_func_io_func_flag_T_1 = EX_IO_bits_br_type == 4'h8;	// @[playground/src/EX_stage.scala:27:44]
  Alu Alu (	// @[playground/src/EX_stage.scala:16:17]
    .io_op     (EX_IO_bits_alu_op),
    .io_src1   (EX_IO_bits_src1),
    .io_src2   (EX_IO_bits_src2),
    .io_result (_Alu_io_result)
  );
  dpi_func dpi_func (	// @[playground/src/EX_stage.scala:63:22]
    .clock     (clock),
    .reset     (reset),
    .func_flag (_dpi_func_io_is_jal_T | _dpi_func_io_func_flag_T_1),	// @[playground/src/EX_stage.scala:26:44, :27:44, :66:55]
    .is_jal    (_dpi_func_io_is_jal_T),	// @[playground/src/EX_stage.scala:26:44]
    .pc        (EX_IO_bits_nextpc),
    .nextpc    (32'h0),	// @[playground/src/EX_stage.scala:34:52]
    .rd        ({27'h0, EX_IO_bits_rd}),	// @[playground/src/EX_stage.scala:70:17]
    .inst      (EX_IO_bits_inst)
  );
  assign EX_to_ls_bits_pc_sel = EX_IO_bits_pc_sel;	// @[<stdin>:956:3]
  assign EX_to_ls_bits_csr_addr = EX_IO_bits_csr_addr;	// @[<stdin>:956:3]
  assign EX_to_ls_bits_csr_cmd = EX_IO_bits_csr_cmd;	// @[<stdin>:956:3]
  assign EX_to_ls_bits_st_type = EX_IO_bits_st_type;	// @[<stdin>:956:3]
  assign EX_to_ls_bits_ld_type = EX_IO_bits_ld_type;	// @[<stdin>:956:3]
  assign EX_to_ls_bits_ebreak_flag = EX_IO_bits_ebreak_flag;	// @[<stdin>:956:3]
  assign EX_to_ls_bits_wb_sel = EX_IO_bits_wb_sel;	// @[<stdin>:956:3]
  assign EX_to_ls_bits_wen = EX_IO_bits_wen;	// @[<stdin>:956:3]
  assign EX_to_ls_bits_rd = EX_IO_bits_rd;	// @[<stdin>:956:3]
  assign EX_to_ls_bits_rdata2 = EX_IO_bits_rdata2;	// @[<stdin>:956:3]
  assign EX_to_ls_bits_result = _Alu_io_result;	// @[<stdin>:956:3, playground/src/EX_stage.scala:16:17]
  assign EX_to_ls_bits_nextpc = EX_IO_bits_nextpc;	// @[<stdin>:956:3]
  assign EX_to_ls_bits_pc = EX_IO_bits_pc;	// @[<stdin>:956:3]
  assign EX_br_bus_is_jump =
    _dpi_func_io_is_jal_T | _dpi_func_io_func_flag_T_1 | EX_IO_bits_br_type == 4'h3
    & rs1_eq_rs2 | EX_IO_bits_br_type == 4'h6 & ~rs1_eq_rs2 | EX_IO_bits_br_type == 4'h2
    & rs1_lt_rs2_s | EX_IO_bits_br_type == 4'h1 & rs1_lt_rs2_u
    | EX_IO_bits_br_type == 4'h5 & ~rs1_lt_rs2_s | EX_IO_bits_br_type == 4'h4
    & ~rs1_lt_rs2_u;	// @[<stdin>:956:3, playground/src/EX_stage.scala:22:40, :23:47, :24:41, :26:44, :27:44, :28:{45,55}, :29:{45,55,58}, :30:{45,55}, :31:{45,55}, :32:{45,55,58}, :33:{23,45,55,58}]
  assign EX_br_bus_dnpc =
    EX_IO_bits_br_type == 4'h8
      ? {_Alu_io_result[31:1], 1'h0}
      : EX_IO_bits_br_type == 4'h7 | EX_IO_bits_br_type == 4'h6
        | EX_IO_bits_br_type == 4'h5 | EX_IO_bits_br_type == 4'h4
        | EX_IO_bits_br_type == 4'h3 | EX_IO_bits_br_type == 4'h2
        | EX_IO_bits_br_type == 4'h1
          ? _Alu_io_result
          : 32'h0;	// @[<stdin>:956:3, playground/src/EX_stage.scala:13:14, :16:17, :26:44, :27:44, :28:45, :29:45, :30:45, :31:45, :32:45, :33:45, :34:52, :43:{18,32}]
endmodule

