// Generated by CIRCT firtool-1.56.0
module EXE_stage(	// @[<stdin>:606:3]
  input         clock,	// @[<stdin>:607:11]
                reset,	// @[<stdin>:608:11]
                io_d_ebus_is_ebreak,	// @[playground/src/EXE_stage.scala:4:12]
                io_d_ebus_data_wen,	// @[playground/src/EXE_stage.scala:4:12]
                io_d_ebus_result_is_imm,	// @[playground/src/EXE_stage.scala:4:12]
                io_d_ebus_result_is_snpc,	// @[playground/src/EXE_stage.scala:4:12]
                io_d_ebus_src_is_sign,	// @[playground/src/EXE_stage.scala:4:12]
                io_d_ebus_src1_is_pc,	// @[playground/src/EXE_stage.scala:4:12]
                io_d_ebus_src2_is_imm,	// @[playground/src/EXE_stage.scala:4:12]
                io_d_ebus_src2_is_shamt_imm,	// @[playground/src/EXE_stage.scala:4:12]
                io_d_ebus_src2_is_shamt_src,	// @[playground/src/EXE_stage.scala:4:12]
                io_d_ebus_sram_valid,	// @[playground/src/EXE_stage.scala:4:12]
                io_d_ebus_sram_wen,	// @[playground/src/EXE_stage.scala:4:12]
  input  [3:0]  io_d_ebus_wmask,	// @[playground/src/EXE_stage.scala:4:12]
  input  [31:0] io_d_ebus_snpc,	// @[playground/src/EXE_stage.scala:4:12]
                io_d_ebus_imm,	// @[playground/src/EXE_stage.scala:4:12]
  input  [4:0]  io_d_ebus_src1,	// @[playground/src/EXE_stage.scala:4:12]
                io_d_ebus_src2,	// @[playground/src/EXE_stage.scala:4:12]
                io_d_ebus_rd,	// @[playground/src/EXE_stage.scala:4:12]
  input         io_d_ebus_alu_op_0,	// @[playground/src/EXE_stage.scala:4:12]
                io_d_ebus_alu_op_1,	// @[playground/src/EXE_stage.scala:4:12]
                io_d_ebus_alu_op_2,	// @[playground/src/EXE_stage.scala:4:12]
                io_d_ebus_alu_op_3,	// @[playground/src/EXE_stage.scala:4:12]
                io_d_ebus_alu_op_4,	// @[playground/src/EXE_stage.scala:4:12]
                io_d_ebus_alu_op_5,	// @[playground/src/EXE_stage.scala:4:12]
                io_d_ebus_alu_op_6,	// @[playground/src/EXE_stage.scala:4:12]
                io_d_ebus_alu_op_7,	// @[playground/src/EXE_stage.scala:4:12]
                io_d_ebus_alu_op_8,	// @[playground/src/EXE_stage.scala:4:12]
  input  [31:0] io_pc,	// @[playground/src/EXE_stage.scala:4:12]
  output [31:0] io_result,	// @[playground/src/EXE_stage.scala:4:12]
                io_jalr_taget	// @[playground/src/EXE_stage.scala:4:12]
);

  wire [31:0] _alu_io_result;	// @[playground/src/EXE_stage.scala:22:18]
  wire [31:0] _RegFile_io_rdata1;	// @[playground/src/EXE_stage.scala:12:21]
  wire [31:0] _RegFile_io_rdata2;	// @[playground/src/EXE_stage.scala:12:21]
  wire [31:0] _io_result_output =
    io_d_ebus_result_is_imm
      ? io_d_ebus_imm
      : io_d_ebus_result_is_snpc ? io_d_ebus_snpc : _alu_io_result;	// @[playground/src/EXE_stage.scala:22:18, :33:17, :34:18]
  wire [31:0] _jalr_tmp_T = _alu_io_result + io_d_ebus_imm;	// @[playground/src/EXE_stage.scala:22:18, :35:29]
  RegFile RegFile (	// @[playground/src/EXE_stage.scala:12:21]
    .clock     (clock),
    .reset     (reset),
    .io_waddr  (io_d_ebus_rd),
    .io_wdata  (_io_result_output),	// @[playground/src/EXE_stage.scala:33:17]
    .io_raddr1 (io_d_ebus_is_ebreak ? 5'hA : io_d_ebus_src1),	// @[playground/src/EXE_stage.scala:15:25]
    .io_raddr2 (io_d_ebus_is_ebreak ? 5'h0 : io_d_ebus_src2),	// @[playground/src/EXE_stage.scala:16:25]
    .io_wen    (io_d_ebus_data_wen),
    .io_rdata1 (_RegFile_io_rdata1),
    .io_rdata2 (_RegFile_io_rdata2)
  );
  Alu alu (	// @[playground/src/EXE_stage.scala:22:18]
    .io_op
      ({3'h0,
        io_d_ebus_alu_op_8,
        io_d_ebus_alu_op_7,
        io_d_ebus_alu_op_6,
        io_d_ebus_alu_op_5,
        io_d_ebus_alu_op_4,
        io_d_ebus_alu_op_3,
        io_d_ebus_alu_op_2,
        io_d_ebus_alu_op_1,
        io_d_ebus_alu_op_0}),	// @[playground/src/EXE_stage.scala:28:33]
    .io_src1   (io_d_ebus_src1_is_pc ? io_pc : _RegFile_io_rdata1),	// @[playground/src/EXE_stage.scala:12:21, :23:19]
    .io_src2
      (io_d_ebus_src2_is_imm
         ? io_d_ebus_imm
         : io_d_ebus_src2_is_shamt_imm
             ? {26'h0, io_d_ebus_imm[5:0]}
             : io_d_ebus_src2_is_shamt_src
                 ? {26'h0, _RegFile_io_rdata2[5:0]}
                 : _RegFile_io_rdata2),	// @[playground/src/EXE_stage.scala:12:21, :24:19, :25:{20,62}, :26:{22,60}]
    .io_sign   (io_d_ebus_src_is_sign),
    .io_result (_alu_io_result)
  );
  pmem_dpi pmem_dpi (	// @[playground/src/EXE_stage.scala:39:22]
    .clock      (clock),
    .reset      (reset),
    .sram_valid (io_d_ebus_sram_valid),
    .sram_wen   (io_d_ebus_sram_wen),
    .raddr      (_alu_io_result),	// @[playground/src/EXE_stage.scala:22:18]
    .waddr      (_alu_io_result),	// @[playground/src/EXE_stage.scala:22:18]
    .wdata      ({27'h0, io_d_ebus_src2}),	// @[playground/src/EXE_stage.scala:47:20]
    .wmask      ({1'h0, io_d_ebus_wmask}),	// @[playground/src/EXE_stage.scala:10:12, :48:20]
    .rdata      (/* unused */)
  );
  assign io_result = _io_result_output;	// @[<stdin>:606:3, playground/src/EXE_stage.scala:33:17]
  assign io_jalr_taget = {_jalr_tmp_T[31:1], 1'h0};	// @[<stdin>:606:3, playground/src/EXE_stage.scala:10:12, :35:29, :36:{21,30}]
endmodule

