// Generated by CIRCT firtool-1.56.0
// external module read_inst

// external module dpi_ls

// external module csr_debug_dpic

// external module dpi_getinfo

// external module dpi_inv

// external module dpi_func

// external module dpi_ebreak

