// Generated by CIRCT firtool-1.56.0
// external module read_inst

// external module dpi_csrdebug

// external module Dpi_GetInfo

// external module dpi_inv

// external module Dpi_Func

// external module Dpi_Ebreak

// external module Dpi_CsrCommit

// external module dpi_sram

