// Generated by CIRCT firtool-1.56.0
module ID_stage(	// @[<stdin>:61:3]
  input         clock,	// @[<stdin>:62:11]
                reset,	// @[<stdin>:63:11]
  input  [31:0] io_pc,	// @[playground/src/ID_stage.scala:6:12]
                io_nextpc,	// @[playground/src/ID_stage.scala:6:12]
                io_inst,	// @[playground/src/ID_stage.scala:6:12]
                io_result,	// @[playground/src/ID_stage.scala:6:12]
                io_f_dbus_snpc,	// @[playground/src/ID_stage.scala:6:12]
  output [31:0] io_Imm,	// @[playground/src/ID_stage.scala:6:12]
  output        io_is_not_jalr,	// @[playground/src/ID_stage.scala:6:12]
                io_d_ebus_is_ebreak,	// @[playground/src/ID_stage.scala:6:12]
                io_d_ebus_data_wen,	// @[playground/src/ID_stage.scala:6:12]
                io_d_ebus_result_is_imm,	// @[playground/src/ID_stage.scala:6:12]
                io_d_ebus_result_is_snpc,	// @[playground/src/ID_stage.scala:6:12]
                io_d_ebus_src_is_sign,	// @[playground/src/ID_stage.scala:6:12]
                io_d_ebus_src1_is_pc,	// @[playground/src/ID_stage.scala:6:12]
                io_d_ebus_src2_is_imm,	// @[playground/src/ID_stage.scala:6:12]
                io_d_ebus_src2_is_shamt_imm,	// @[playground/src/ID_stage.scala:6:12]
                io_d_ebus_src2_is_shamt_src,	// @[playground/src/ID_stage.scala:6:12]
                io_d_ebus_sram_valid,	// @[playground/src/ID_stage.scala:6:12]
                io_d_ebus_sram_wen,	// @[playground/src/ID_stage.scala:6:12]
  output [3:0]  io_d_ebus_wmask,	// @[playground/src/ID_stage.scala:6:12]
  output [31:0] io_d_ebus_snpc,	// @[playground/src/ID_stage.scala:6:12]
                io_d_ebus_imm,	// @[playground/src/ID_stage.scala:6:12]
  output [4:0]  io_d_ebus_src1,	// @[playground/src/ID_stage.scala:6:12]
                io_d_ebus_src2,	// @[playground/src/ID_stage.scala:6:12]
                io_d_ebus_rd,	// @[playground/src/ID_stage.scala:6:12]
  output        io_d_ebus_alu_op_0,	// @[playground/src/ID_stage.scala:6:12]
                io_d_ebus_alu_op_1,	// @[playground/src/ID_stage.scala:6:12]
                io_d_ebus_alu_op_2,	// @[playground/src/ID_stage.scala:6:12]
                io_d_ebus_alu_op_3,	// @[playground/src/ID_stage.scala:6:12]
                io_d_ebus_alu_op_4,	// @[playground/src/ID_stage.scala:6:12]
                io_d_ebus_alu_op_5,	// @[playground/src/ID_stage.scala:6:12]
                io_d_ebus_alu_op_6,	// @[playground/src/ID_stage.scala:6:12]
                io_d_ebus_alu_op_7,	// @[playground/src/ID_stage.scala:6:12]
                io_d_ebus_alu_op_8	// @[playground/src/ID_stage.scala:6:12]
);

  wire        IsaI_ebreak = 1'h0;	// @[playground/src/ID_stage.scala:22:26, :31:19]
  wire        IsaU_lui = io_inst[6:0] == 7'h37;	// @[playground/src/ID_stage.scala:25:26, :40:24]
  wire        IsaU_auipc = io_inst[6:0] == 7'h17;	// @[playground/src/ID_stage.scala:25:26, :40:24, :41:24]
  wire        IsaU_jal = io_inst[6:0] == 7'h6F;	// @[playground/src/ID_stage.scala:25:26, :40:24, :42:24]
  wire [9:0]  _GEN = {io_inst[14:12], io_inst[6:0]};	// @[playground/src/ID_stage.scala:40:24, :43:24]
  wire        IsaI_jalr = _GEN == 10'h67;	// @[playground/src/ID_stage.scala:22:26, :43:24]
  wire        IsaB_beq = _GEN == 10'h63;	// @[playground/src/ID_stage.scala:24:26, :43:24, :44:24]
  wire        IsaB_bne = _GEN == 10'hE3;	// @[playground/src/ID_stage.scala:24:26, :43:24, :45:24]
  wire        IsaB_blt = _GEN == 10'h263;	// @[playground/src/ID_stage.scala:24:26, :43:24, :46:24]
  wire        IsaB_bge = _GEN == 10'h2E3;	// @[playground/src/ID_stage.scala:24:26, :43:24, :47:24]
  wire        IsaB_bltu = _GEN == 10'h363;	// @[playground/src/ID_stage.scala:24:26, :43:24, :48:24]
  wire        IsaB_bgeu = _GEN == 10'h3E3;	// @[playground/src/ID_stage.scala:24:26, :43:24, :49:24]
  wire        IsaI_lb = _GEN == 10'h3;	// @[playground/src/ID_stage.scala:22:26, :43:24, :50:24]
  wire        IsaI_lh = _GEN == 10'h83;	// @[playground/src/ID_stage.scala:22:26, :43:24, :51:24]
  wire        IsaI_lw = _GEN == 10'h103;	// @[playground/src/ID_stage.scala:22:26, :43:24, :52:24]
  wire        IsaI_lbu = _GEN == 10'h203;	// @[playground/src/ID_stage.scala:22:26, :43:24, :53:24]
  wire        IsaI_lhu = _GEN == 10'h283;	// @[playground/src/ID_stage.scala:22:26, :43:24, :54:24]
  wire        IsaS_sb = _GEN == 10'h23;	// @[playground/src/ID_stage.scala:23:26, :43:24, :55:24]
  wire        IsaS_sh = _GEN == 10'hA3;	// @[playground/src/ID_stage.scala:23:26, :43:24, :56:24]
  wire        IsaS_sw = _GEN == 10'h123;	// @[playground/src/ID_stage.scala:23:26, :43:24, :57:24]
  wire        IsaI_addi = _GEN == 10'h13;	// @[playground/src/ID_stage.scala:22:26, :43:24, :58:24]
  wire        IsaI_slti = _GEN == 10'h113;	// @[playground/src/ID_stage.scala:22:26, :43:24, :59:24]
  wire        IsaI_sltiu = _GEN == 10'h193;	// @[playground/src/ID_stage.scala:22:26, :43:24, :60:24]
  wire        IsaI_xori = _GEN == 10'h213;	// @[playground/src/ID_stage.scala:22:26, :43:24, :61:24]
  wire        IsaI_ori = _GEN == 10'h313;	// @[playground/src/ID_stage.scala:22:26, :43:24, :62:24]
  wire        IsaI_andi = _GEN == 10'h393;	// @[playground/src/ID_stage.scala:22:26, :43:24, :63:24]
  wire [16:0] _GEN_0 = {io_inst[31:25], io_inst[14:12], io_inst[6:0]};	// @[playground/src/ID_stage.scala:40:24, :43:24, :64:24]
  wire        IsaI_slli = _GEN_0 == 17'h93;	// @[playground/src/ID_stage.scala:22:26, :64:24]
  wire        IsaI_srli = _GEN_0 == 17'h293;	// @[playground/src/ID_stage.scala:22:26, :64:24, :65:24]
  wire        IsaI_srai = _GEN_0 == 17'h8293;	// @[playground/src/ID_stage.scala:22:26, :64:24, :66:24]
  wire        IsaR_add = _GEN_0 == 17'h33;	// @[playground/src/ID_stage.scala:21:26, :64:24, :67:24]
  wire        IsaR_sub = _GEN_0 == 17'h8033;	// @[playground/src/ID_stage.scala:21:26, :64:24, :68:24]
  wire        IsaR_sll = _GEN_0 == 17'hB3;	// @[playground/src/ID_stage.scala:21:26, :64:24, :69:24]
  wire        IsaR_slt = _GEN_0 == 17'h133;	// @[playground/src/ID_stage.scala:21:26, :64:24, :70:24]
  wire        IsaR_sltu = _GEN_0 == 17'h1B3;	// @[playground/src/ID_stage.scala:21:26, :64:24, :71:24]
  wire        IsaR_xor = _GEN_0 == 17'h233;	// @[playground/src/ID_stage.scala:21:26, :64:24, :72:24]
  wire        IsaR_srl = _GEN_0 == 17'h2B3;	// @[playground/src/ID_stage.scala:21:26, :64:24, :73:24]
  wire        IsaR_sra = _GEN_0 == 17'h82B3;	// @[playground/src/ID_stage.scala:21:26, :64:24, :74:24]
  wire        IsaR_or = _GEN_0 == 17'h333;	// @[playground/src/ID_stage.scala:21:26, :64:24, :75:24]
  wire        IsaR_and = _GEN_0 == 17'h3B3;	// @[playground/src/ID_stage.scala:21:26, :64:24, :76:24]
  wire [4:0]  _io_Imm_T =
    {|{IsaI_jalr,
       IsaI_lb,
       IsaI_lh,
       IsaI_lw,
       IsaI_lbu,
       IsaI_lhu,
       IsaI_addi,
       IsaI_slti,
       IsaI_sltiu,
       IsaI_xori,
       IsaI_ori,
       IsaI_andi,
       IsaI_slli,
       IsaI_srli,
       IsaI_srai,
       IsaI_ebreak},
     |{IsaS_sb, IsaS_sh, IsaS_sw},
     |{IsaB_beq, IsaB_bne, IsaB_blt, IsaB_bge, IsaB_bltu, IsaB_bgeu},
     |{IsaU_lui, IsaU_auipc, IsaU_jal},
     IsaU_jal};	// @[playground/src/ID_stage.scala:22:26, :23:26, :24:26, :25:26, :87:{30,36}, :88:{30,36}, :89:{30,36}, :90:{30,36}, :92:31]
  wire [31:0] _io_Imm_output =
    _io_Imm_T == 5'h3
      ? {{12{io_inst[19]}}, io_inst[19:12], io_inst[20], io_inst[30:21], 1'h0}
      : _io_Imm_T == 5'h2
          ? {io_inst[31:12], 12'h0}
          : _io_Imm_T == 5'h4
              ? {{21{io_inst[7]}}, io_inst[30:25], io_inst[11:8], 1'h0}
              : _io_Imm_T == 5'h8
                  ? {{20{io_inst[31]}}, io_inst[31:25], io_inst[11:7]}
                  : _io_Imm_T == 5'h10 ? {{20{io_inst[31]}}, io_inst[31:20]} : 32'h0;	// @[playground/src/Bundle.scala:101:{10,15,37}, playground/src/ID_stage.scala:29:23, :30:{27,42}, :31:{19,39,50,65}, :32:{19,27}, :33:{39,54,66}, :92:{31,42}]
  wire        _io_d_ebus_alu_op_0_T = IsaI_addi | IsaR_add;	// @[playground/src/ID_stage.scala:21:26, :22:26, :100:34]
  wire        _singal_dpi_io_func_flag_T = IsaU_jal | IsaI_jalr;	// @[playground/src/ID_stage.scala:22:26, :25:26, :106:38]
  wire        _io_d_ebus_alu_op_7_T = IsaI_srai | IsaR_sra;	// @[playground/src/ID_stage.scala:21:26, :22:26, :107:36]
  wire        _io_d_ebus_sram_valid_output =
    IsaI_lb | IsaI_lh | IsaI_lw | IsaI_lbu | IsaI_lhu | IsaS_sb | IsaS_sh | IsaS_sw;	// @[playground/src/ID_stage.scala:22:26, :23:26, :114:95]
  singal_dpi singal_dpi (	// @[playground/src/ID_stage.scala:165:24]
    .clock       (clock),
    .reset       (reset),
    .pc          (io_pc),
    .nextpc      (io_nextpc),
    .inst        (io_inst),
    .rd          ({27'h0, io_inst[11:7]}),	// @[playground/src/ID_stage.scala:30:42, :41:24, :171:19]
    .is_jal      (IsaU_jal),	// @[playground/src/ID_stage.scala:25:26]
    .func_flag   (_singal_dpi_io_func_flag_T),	// @[playground/src/ID_stage.scala:106:38]
    .ebreak_flag (IsaI_ebreak),	// @[playground/src/ID_stage.scala:22:26]
    .inv_flag    (1'h0),	// @[playground/src/ID_stage.scala:31:19]
    .ret_reg     (io_result)
  );
  assign io_Imm = _io_Imm_output;	// @[<stdin>:61:3, playground/src/ID_stage.scala:92:42]
  assign io_is_not_jalr =
    IsaU_jal | IsaB_beq | IsaB_bne | IsaB_blt | IsaB_bltu | IsaB_bge | IsaB_bgeu;	// @[<stdin>:61:3, playground/src/ID_stage.scala:24:26, :25:26, :125:73]
  assign io_d_ebus_is_ebreak = IsaI_ebreak;	// @[<stdin>:61:3, playground/src/ID_stage.scala:22:26]
  assign io_d_ebus_data_wen =
    _io_d_ebus_alu_op_0_T | IsaI_andi | IsaR_and | IsaU_lui | IsaR_slt | IsaR_sltu
    | IsaR_sub | IsaI_ori | IsaR_or | IsaI_xori | IsaR_xor | IsaI_jalr | IsaU_jal
    | IsaU_auipc | IsaI_slti | IsaI_sltiu | IsaI_slli | IsaI_srai | IsaI_srli | IsaR_sll
    | IsaR_sra | IsaR_srl;	// @[<stdin>:61:3, playground/src/ID_stage.scala:21:26, :22:26, :25:26, :100:34, :104:57]
  assign io_d_ebus_result_is_imm = IsaU_lui;	// @[<stdin>:61:3, playground/src/ID_stage.scala:25:26]
  assign io_d_ebus_result_is_snpc = _singal_dpi_io_func_flag_T;	// @[<stdin>:61:3, playground/src/ID_stage.scala:106:38]
  assign io_d_ebus_src_is_sign = _io_d_ebus_alu_op_7_T | IsaR_slt | IsaB_blt | IsaB_bltu;	// @[<stdin>:61:3, playground/src/ID_stage.scala:21:26, :24:26, :107:{36,70}]
  assign io_d_ebus_src1_is_pc = IsaU_auipc;	// @[<stdin>:61:3, playground/src/ID_stage.scala:25:26]
  assign io_d_ebus_src2_is_imm =
    IsaI_addi | IsaI_slti | IsaI_sltiu | IsaI_xori | IsaI_ori | IsaI_andi | IsaI_jalr
    | IsaU_auipc | IsaI_lb | IsaI_lh | IsaI_lw | IsaI_lbu | IsaI_lhu;	// @[<stdin>:61:3, playground/src/ID_stage.scala:22:26, :25:26, :111:65]
  assign io_d_ebus_src2_is_shamt_imm = IsaI_slli | IsaI_srai | IsaI_srli;	// @[<stdin>:61:3, playground/src/ID_stage.scala:22:26, :112:54]
  assign io_d_ebus_src2_is_shamt_src = IsaR_sll | IsaR_sra | IsaR_srl;	// @[<stdin>:61:3, playground/src/ID_stage.scala:21:26, :113:54]
  assign io_d_ebus_sram_valid = _io_d_ebus_sram_valid_output;	// @[<stdin>:61:3, playground/src/ID_stage.scala:114:95]
  assign io_d_ebus_sram_wen = IsaS_sb | IsaS_sh | IsaS_sw;	// @[<stdin>:61:3, playground/src/ID_stage.scala:23:26, :115:41]
  assign io_d_ebus_wmask =
    IsaI_lb | IsaI_lbu ? 4'h1 : IsaI_lh | IsaI_lhu ? 4'h3 : {4{IsaI_lw}};	// @[<stdin>:61:3, playground/src/ID_stage.scala:22:26, :116:{23,32}, :117:{23,32}, :118:24]
  assign io_d_ebus_snpc = io_f_dbus_snpc;	// @[<stdin>:61:3]
  assign io_d_ebus_imm = _io_Imm_output;	// @[<stdin>:61:3, playground/src/ID_stage.scala:92:42]
  assign io_d_ebus_src1 = io_inst[19:15];	// @[<stdin>:61:3, playground/src/ID_stage.scala:35:23]
  assign io_d_ebus_src2 = io_inst[24:20];	// @[<stdin>:61:3, playground/src/ID_stage.scala:34:23]
  assign io_d_ebus_rd = io_inst[11:7];	// @[<stdin>:61:3, playground/src/ID_stage.scala:30:42]
  assign io_d_ebus_alu_op_0 =
    _io_d_ebus_alu_op_0_T | IsaI_ebreak | IsaI_jalr | IsaU_auipc
    | _io_d_ebus_sram_valid_output;	// @[<stdin>:61:3, playground/src/ID_stage.scala:22:26, :25:26, :100:34, :114:95, :128:15]
  assign io_d_ebus_alu_op_1 = IsaR_sub;	// @[<stdin>:61:3, playground/src/ID_stage.scala:21:26]
  assign io_d_ebus_alu_op_2 = IsaI_andi | IsaR_and;	// @[<stdin>:61:3, playground/src/ID_stage.scala:21:26, :22:26, :132:35]
  assign io_d_ebus_alu_op_3 = IsaI_ori | IsaR_or;	// @[<stdin>:61:3, playground/src/ID_stage.scala:21:26, :22:26, :134:35]
  assign io_d_ebus_alu_op_4 = IsaI_xori | IsaR_xor;	// @[<stdin>:61:3, playground/src/ID_stage.scala:21:26, :22:26, :136:35]
  assign io_d_ebus_alu_op_5 = IsaR_slt | IsaR_sltu | IsaI_slti | IsaI_sltiu;	// @[<stdin>:61:3, playground/src/ID_stage.scala:21:26, :22:26, :138:58]
  assign io_d_ebus_alu_op_6 = IsaI_slli | IsaR_sll;	// @[<stdin>:61:3, playground/src/ID_stage.scala:21:26, :22:26, :140:35]
  assign io_d_ebus_alu_op_7 = _io_d_ebus_alu_op_7_T;	// @[<stdin>:61:3, playground/src/ID_stage.scala:107:36]
  assign io_d_ebus_alu_op_8 = IsaI_srli | IsaR_srl;	// @[<stdin>:61:3, playground/src/ID_stage.scala:21:26, :22:26, :144:35]
endmodule

