// Generated by CIRCT firtool-1.56.0
module SimTop(	// @[<stdin>:121:3]
  input         clock,	// @[<stdin>:122:11]
                reset,	// @[<stdin>:123:11]
  input  [31:0] io_inst,	// @[playground/src/SimTop.scala:6:14]
  output [31:0] io_pc,	// @[playground/src/SimTop.scala:6:14]
                io_result,	// @[playground/src/SimTop.scala:6:14]
  output        io_wen,	// @[playground/src/SimTop.scala:6:14]
  output [31:0] io_imm	// @[playground/src/SimTop.scala:6:14]
);

  wire [31:0] Imm;	// @[playground/src/SimTop.scala:99:39]
  wire        IsaI_jalr;	// @[playground/src/SimTop.scala:52:24]
  wire [31:0] _alu_io_result;	// @[playground/src/SimTop.scala:157:18]
  wire [31:0] _RegFile_io_rdata1;	// @[playground/src/SimTop.scala:149:21]
  wire [31:0] _RegFile_io_rdata2;	// @[playground/src/SimTop.scala:149:21]
  reg  [31:0] pc;	// @[playground/src/SimTop.scala:25:17]
  wire [31:0] _dnpc_T_4 = pc + Imm;	// @[playground/src/SimTop.scala:25:17, :26:29, :99:39]
  wire        IsaU_lui = io_inst[6:0] == 7'h37;	// @[playground/src/SimTop.scala:49:24]
  wire        IsaU_auipc = io_inst[6:0] == 7'h17;	// @[playground/src/SimTop.scala:49:24, :50:24]
  wire        ImmType_ImmJType = io_inst[6:0] == 7'h6F;	// @[playground/src/SimTop.scala:49:24, :51:24]
  wire [9:0]  _GEN = {io_inst[14:12], io_inst[6:0]};	// @[playground/src/SimTop.scala:49:24, :52:24]
  assign IsaI_jalr = _GEN == 10'h67;	// @[playground/src/SimTop.scala:52:24]
  wire        IsaB_beq = _GEN == 10'h63;	// @[playground/src/SimTop.scala:52:24, :53:24]
  wire        IsaB_bne = _GEN == 10'hE3;	// @[playground/src/SimTop.scala:52:24, :54:24]
  wire        IsaB_blt = _GEN == 10'h263;	// @[playground/src/SimTop.scala:52:24, :55:24]
  wire        IsaB_bge = _GEN == 10'h2E3;	// @[playground/src/SimTop.scala:52:24, :56:24]
  wire        IsaB_bltu = _GEN == 10'h363;	// @[playground/src/SimTop.scala:52:24, :57:24]
  wire        IsaB_bgeu = _GEN == 10'h3E3;	// @[playground/src/SimTop.scala:52:24, :58:24]
  wire        IsaI_addi = _GEN == 10'h13;	// @[playground/src/SimTop.scala:52:24, :67:24]
  wire        IsaI_slti = _GEN == 10'h113;	// @[playground/src/SimTop.scala:52:24, :68:24]
  wire        IsaI_sltiu = _GEN == 10'h193;	// @[playground/src/SimTop.scala:52:24, :69:24]
  wire        IsaI_xori = _GEN == 10'h213;	// @[playground/src/SimTop.scala:52:24, :70:24]
  wire        IsaI_ori = _GEN == 10'h313;	// @[playground/src/SimTop.scala:52:24, :71:24]
  wire        IsaI_andi = _GEN == 10'h393;	// @[playground/src/SimTop.scala:52:24, :72:24]
  wire [16:0] _GEN_0 = {io_inst[31:25], io_inst[14:12], io_inst[6:0]};	// @[playground/src/SimTop.scala:49:24, :52:24, :73:24]
  wire        IsaI_slli = _GEN_0 == 17'h93;	// @[playground/src/SimTop.scala:73:24]
  wire        IsaI_srli = _GEN_0 == 17'h293;	// @[playground/src/SimTop.scala:73:24, :74:24]
  wire        IsaI_srai = _GEN_0 == 17'h8293;	// @[playground/src/SimTop.scala:73:24, :75:24]
  wire        alu_op_1 = _GEN_0 == 17'h8033;	// @[playground/src/SimTop.scala:73:24, :77:24]
  wire        IsaR_sll = _GEN_0 == 17'hB3;	// @[playground/src/SimTop.scala:73:24, :78:24]
  wire        IsaR_slt = _GEN_0 == 17'h133;	// @[playground/src/SimTop.scala:73:24, :79:24]
  wire        IsaR_sltu = _GEN_0 == 17'h1B3;	// @[playground/src/SimTop.scala:73:24, :80:24]
  wire        IsaR_xor = _GEN_0 == 17'h233;	// @[playground/src/SimTop.scala:73:24, :81:24]
  wire        IsaR_srl = _GEN_0 == 17'h2B3;	// @[playground/src/SimTop.scala:73:24, :82:24]
  wire        IsaR_sra = _GEN_0 == 17'h82B3;	// @[playground/src/SimTop.scala:73:24, :83:24]
  wire        IsaR_or = _GEN_0 == 17'h333;	// @[playground/src/SimTop.scala:73:24, :84:24]
  wire        IsaR_and = _GEN_0 == 17'h3B3;	// @[playground/src/SimTop.scala:73:24, :85:24]
  wire        IsaI_ebreak = io_inst == 32'h100073;	// @[playground/src/SimTop.scala:88:24]
  wire [4:0]  _Imm_T =
    {|{IsaI_jalr,
       _GEN == 10'h3,
       _GEN == 10'h83,
       _GEN == 10'h103,
       _GEN == 10'h203,
       _GEN == 10'h283,
       IsaI_addi,
       IsaI_slti,
       IsaI_sltiu,
       IsaI_xori,
       IsaI_ori,
       IsaI_andi,
       IsaI_slli,
       IsaI_srli,
       IsaI_srai,
       IsaI_ebreak},
     |{_GEN == 10'h23, _GEN == 10'hA3, _GEN == 10'h123},
     |{IsaB_beq, IsaB_bne, IsaB_blt, IsaB_bge, IsaB_bltu, IsaB_bgeu},
     |{IsaU_lui, IsaU_auipc, ImmType_ImmJType},
     ImmType_ImmJType};	// @[playground/src/SimTop.scala:49:24, :50:24, :51:24, :52:24, :53:24, :54:24, :55:24, :56:24, :57:24, :58:24, :59:24, :60:24, :61:24, :62:24, :63:24, :64:24, :65:24, :66:24, :67:24, :68:24, :69:24, :70:24, :71:24, :72:24, :73:24, :74:24, :75:24, :88:24, :94:{30,36}, :95:{30,36}, :96:{30,36}, :97:{30,36}, :99:28]
  assign Imm =
    _Imm_T == 5'h3
      ? {{12{io_inst[19]}}, io_inst[19:12], io_inst[20], io_inst[30:21], 1'h0}
      : _Imm_T == 5'h2
          ? {io_inst[31:12], 12'h0}
          : _Imm_T == 5'h4
              ? {{21{io_inst[7]}}, io_inst[30:25], io_inst[11:8], 1'h0}
              : _Imm_T == 5'h8
                  ? {{20{io_inst[31]}}, io_inst[31:25], io_inst[11:7]}
                  : _Imm_T == 5'h10 ? {{20{io_inst[31]}}, io_inst[31:20]} : 32'h0;	// @[playground/src/Bundle.scala:76:{10,15,37}, playground/src/SimTop.scala:26:34, :38:23, :39:{27,42}, :40:{19,39,50,65}, :41:{19,27}, :42:{39,54,66}, :99:{28,39}]
  wire        alu_op_0 = IsaI_addi | _GEN_0 == 17'h33;	// @[playground/src/SimTop.scala:67:24, :73:24, :76:24, :107:22]
  wire        wen =
    alu_op_0 | IsaI_andi | IsaR_and | IsaU_lui | IsaU_auipc | IsaR_slt | IsaR_sltu
    | alu_op_1 | IsaI_ori | IsaR_or | IsaI_xori | IsaR_xor | IsaI_slti | IsaI_sltiu
    | IsaI_slli | IsaI_srai | IsaI_srli | IsaR_sll | IsaR_sra | IsaR_srl;	// @[playground/src/SimTop.scala:49:24, :50:24, :68:24, :69:24, :70:24, :71:24, :72:24, :73:24, :74:24, :75:24, :77:24, :78:24, :79:24, :80:24, :81:24, :82:24, :83:24, :84:24, :85:24, :107:22, :111:57]
  wire        alu_op_9 = IsaI_srai | IsaR_sra;	// @[playground/src/SimTop.scala:75:24, :83:24, :115:29]
  wire [31:0] _io_result_output =
    IsaU_lui
      ? Imm
      : ImmType_ImmJType | IsaI_jalr ? (IsaI_jalr ? 32'h0 : _dnpc_T_4) : _alu_io_result;	// @[playground/src/SimTop.scala:26:{15,29,34}, :49:24, :51:24, :52:24, :99:39, :114:31, :157:18, :179:17, :180:18]
  always @(posedge clock) begin	// @[<stdin>:122:11]
    if (reset)	// @[<stdin>:122:11]
      pc <= 32'h80000000;	// @[playground/src/SimTop.scala:25:17]
    else if (ImmType_ImmJType | IsaB_beq & _alu_io_result[0] | IsaB_bne
             & ~(_alu_io_result[0]) | IsaB_blt & _alu_io_result[0] | IsaB_bltu
             & _alu_io_result[0] | IsaB_bge & ~(_alu_io_result[0]) | IsaB_bgeu
             & ~(_alu_io_result[0])) begin	// @[playground/src/SimTop.scala:51:24, :53:24, :54:24, :55:24, :56:24, :57:24, :58:24, :157:18, :169:{24,41}, :170:{24,27}, :171:24, :172:24, :173:{24,27}, :174:{13,24,27}]
      if (IsaI_jalr)	// @[playground/src/SimTop.scala:52:24]
        pc <= 32'h0;	// @[playground/src/SimTop.scala:25:17, :26:34]
      else	// @[playground/src/SimTop.scala:52:24]
        pc <= _dnpc_T_4;	// @[playground/src/SimTop.scala:25:17, :26:29]
    end
    else	// @[playground/src/SimTop.scala:174:13]
      pc <= pc + 32'h4;	// @[playground/src/SimTop.scala:25:17, :27:14]
  end // always @(posedge)
  singal_ebreak singal_ebreak (	// @[playground/src/SimTop.scala:89:27]
    .clock (clock),
    .flag  (IsaI_ebreak)	// @[playground/src/SimTop.scala:88:24]
  );
  RegFile RegFile (	// @[playground/src/SimTop.scala:149:21]
    .clock     (clock),
    .reset     (reset),
    .io_waddr  (io_inst[11:7]),	// @[playground/src/SimTop.scala:39:42]
    .io_wdata  (_io_result_output),	// @[playground/src/SimTop.scala:179:17]
    .io_raddr1 (io_inst[19:15]),	// @[playground/src/SimTop.scala:44:23]
    .io_raddr2 (io_inst[24:20]),	// @[playground/src/SimTop.scala:43:23]
    .io_wen    (wen),	// @[playground/src/SimTop.scala:111:57]
    .io_rdata1 (_RegFile_io_rdata1),
    .io_rdata2 (_RegFile_io_rdata2)
  );
  Alu alu (	// @[playground/src/SimTop.scala:157:18]
    .io_op
      ({1'h0,
        IsaI_srli | IsaR_srl,
        alu_op_9,
        IsaI_slli | IsaR_sll,
        IsaB_blt | IsaB_bltu | IsaB_bge | IsaB_bgeu | IsaR_slt | IsaR_sltu | IsaI_slti
          | IsaI_sltiu,
        IsaB_beq | IsaB_bne,
        IsaI_xori | IsaR_xor,
        IsaI_ori | IsaR_or,
        IsaI_andi | IsaR_and,
        1'h0,
        alu_op_1,
        alu_op_0}),	// @[playground/src/SimTop.scala:40:19, :53:24, :54:24, :55:24, :56:24, :57:24, :58:24, :68:24, :69:24, :70:24, :71:24, :72:24, :73:24, :74:24, :77:24, :78:24, :79:24, :80:24, :81:24, :82:24, :84:24, :85:24, :107:22, :115:29, :130:25, :132:25, :134:25, :136:25, :139:25, :141:25, :145:25, :163:23]
    .io_src1   (IsaU_auipc ? pc : _RegFile_io_rdata1),	// @[playground/src/SimTop.scala:25:17, :50:24, :149:21, :158:15]
    .io_src2
      (IsaI_addi | IsaI_slti | IsaI_sltiu | IsaI_xori | IsaI_ori | IsaI_andi
         ? Imm
         : IsaI_slli | IsaI_srai | IsaI_srli
             ? {26'h0, io_inst[25:20]}
             : IsaR_sll | IsaR_sra | IsaR_srl
                 ? {26'h0, _RegFile_io_rdata2[5:0]}
                 : _RegFile_io_rdata2),	// @[playground/src/SimTop.scala:49:24, :67:24, :68:24, :69:24, :70:24, :71:24, :72:24, :73:24, :74:24, :75:24, :78:24, :82:24, :83:24, :99:39, :117:74, :118:47, :119:47, :149:21, :159:15, :160:{16,44}, :161:{18,46}]
    .io_sign   (alu_op_9 | IsaR_slt | IsaB_blt | IsaB_bltu),	// @[playground/src/SimTop.scala:55:24, :57:24, :79:24, :115:{29,63}]
    .io_result (_alu_io_result)
  );
  assign io_pc = pc;	// @[<stdin>:121:3, playground/src/SimTop.scala:25:17]
  assign io_result = _io_result_output;	// @[<stdin>:121:3, playground/src/SimTop.scala:179:17]
  assign io_wen = wen;	// @[<stdin>:121:3, playground/src/SimTop.scala:111:57]
  assign io_imm = Imm;	// @[<stdin>:121:3, playground/src/SimTop.scala:99:39]
endmodule

