// Generated by CIRCT firtool-1.56.0
module SimTop(	// <stdin>:179:3
  input        clock,	// <stdin>:180:11
               reset,	// <stdin>:181:11
               io_ps2_clk,	// playground/src/SimTop.scala:5:14
               io_ps2_data,	// playground/src/SimTop.scala:5:14
  output [6:0] io_seg1,	// playground/src/SimTop.scala:5:14
               io_seg2,	// playground/src/SimTop.scala:5:14
               io_seg5,	// playground/src/SimTop.scala:5:14
               io_seg6	// playground/src/SimTop.scala:5:14
);

  assign io_seg1 = 7'h40;	// <stdin>:179:3, playground/src/SimTop.scala:14:24, :15:24, :16:24, :17:24
  assign io_seg2 = 7'h40;	// <stdin>:179:3, playground/src/SimTop.scala:14:24, :15:24, :16:24, :17:24
  assign io_seg5 = 7'h40;	// <stdin>:179:3, playground/src/SimTop.scala:14:24, :15:24, :16:24, :17:24
  assign io_seg6 = 7'h40;	// <stdin>:179:3, playground/src/SimTop.scala:14:24, :15:24, :16:24, :17:24
endmodule

