// Generated by CIRCT firtool-1.56.0
module SimTop(	// <stdin>:3:3
  input        clock,	// <stdin>:4:11
               reset,	// <stdin>:5:11
  input  [2:0] io_op,	// playground/src/SimTop.scala:5:14
  input  [3:0] io_a,	// playground/src/SimTop.scala:5:14
               io_b,	// playground/src/SimTop.scala:5:14
  output [3:0] io_out,	// playground/src/SimTop.scala:5:14
  output       io_of	// playground/src/SimTop.scala:5:14
);

  wire [4:0]      _GEN = {io_a[3], io_a};	// playground/src/SimTop.scala:13:21
  wire [4:0]      _GEN_0 = {io_b[3], io_b};	// playground/src/SimTop.scala:13:21
  wire [4:0]      op_add = _GEN + _GEN_0;	// playground/src/SimTop.scala:13:21
  wire [4:0]      op_sub = _GEN - _GEN_0;	// playground/src/SimTop.scala:13:21, :16:21
  wire [3:0]      _op_neg_T = ~io_a;	// playground/src/SimTop.scala:19:16
  wire [3:0]      _op_and_T = io_a & io_b;	// playground/src/SimTop.scala:21:21
  wire [3:0]      _op_or_T = io_a | io_b;	// playground/src/SimTop.scala:23:20
  wire [3:0]      _op_xor_T = io_a ^ io_b;	// playground/src/SimTop.scala:25:21
  wire [7:0][4:0] _GEN_1 =
    {{{4'h0, io_a == io_b}},
     {{4'h0, $signed(io_a) < $signed(io_b)}},
     {{_op_xor_T[3], _op_xor_T}},
     {{_op_or_T[3], _op_or_T}},
     {{_op_and_T[3], _op_and_T}},
     {{_op_neg_T[3], _op_neg_T}},
     {op_sub},
     {op_add}};	// playground/src/SimTop.scala:13:21, :16:21, :19:16, :21:21, :23:20, :25:21, :27:25, :29:24, :31:34
  assign io_out = _GEN_1[io_op][3:0];	// <stdin>:3:3, playground/src/SimTop.scala:31:{10,34}
  assign io_of =
    io_op == 3'h1 ? op_sub[3] != io_a[3] : io_op == 3'h0 & op_add[3] != io_a[3];	// <stdin>:3:3, playground/src/SimTop.scala:13:21, :14:{28,31,38}, :16:21, :17:{28,31}, :31:34, :37:33
endmodule

