// Generated by CIRCT firtool-1.56.0
module Sram(	// @[<stdin>:1533:3]
  input         clock,	// @[<stdin>:1534:11]
                reset,	// @[<stdin>:1535:11]
                io_in_st_wen,	// @[playground/src/Sram.scala:6:12]
                io_in_ld_wen,	// @[playground/src/Sram.scala:6:12]
  input  [31:0] io_in_addr,	// @[playground/src/Sram.scala:6:12]
  input  [7:0]  io_in_wmask,	// @[playground/src/Sram.scala:6:12]
  input  [31:0] io_in_wdata,	// @[playground/src/Sram.scala:6:12]
  output [31:0] io_out_rdata	// @[playground/src/Sram.scala:6:12]
);

  dpi_sram dpi_sram (	// @[playground/src/Sram.scala:11:22]
    .clock (clock),
    .addr  (io_in_addr),
    .wdata (io_in_wdata),
    .wmask (io_in_wmask),
    .ena   (io_in_ld_wen & io_in_st_wen & ~reset),	// @[playground/src/Sram.scala:16:{46,49}]
    .wen   (io_in_st_wen),
    .rdata (io_out_rdata)
  );
endmodule

